env:
  browser: true
  es6: true
extends:
  - "plugin:react/recommended"
  - "plugin:@typescript-eslint/recommended"
  - "prettier/react"
  - "prettier/@typescript-eslint"
  - "plugin:prettier/recommended"
globals:
  Atomics: readonly
  SharedArrayBuffer: readonly
parser: "@typescript-eslint/parser"
parserOptions:
  ecmaFeatures:
    jsx: true
  project: "./tsconfig.json"
  ecmaVersion: 2018
  sourceType: module
plugins:
  - promise
  - react
  - prettier
  - "@typescript-eslint"
  - "react-hooks"
settings:
  react:
    version: "detect"
rules:
  "react/prop-types": "off"
  "@typescript-eslint/explicit-function-return-type": 0
  "@typescript-eslint/no-explicit-any": 0
  "no-unused-vars": "off"
  "@typescript-eslint/no-unused-vars": 0
  "@typescript-eslint/no-unused-vars-experimental":
    - error
    - ignoreArgsIfArgsAfterAreUsed: true
  "promise/prefer-await-to-then": error
  "@typescript-eslint/explicit-module-boundary-types": 0
  "@typescript-eslint/camelcase": 0
  "react/jsx-uses-react": 0
  "react/react-in-jsx-scope": 0
